### ISSUE TITLE
Problem while computing

### ISSUE THREAD

**Issue by ga-it** [pieterprovoost/quantr#1]
Awesome package!!!

Problem on missing data field from Yahoo:

Error in `mutate()`:
! Problem while computing `freeCashflow = totalCashFromOperatingActivities + capitalExpenditures`.
Caused by error:
! object 'capitalExpenditures' not found

This occurred on yahoo_financials("JPM")

I assume this needs an error trap on calculations based on missing data fields?

**Comment by pieterprovoost** [comment]
Thanks for reporting! Fixed in 0.4.3.
